//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalStandMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdditionalStandMaterial()
        {
            this.ADMFAPayments = new HashSet<ADMFAPayment>();
        }
    
        public int ID { get; set; }
        public int CompanyId { get; set; }
        public int FairId { get; set; }
        public string StandName { get; set; }
        public string StandCode { get; set; }
        public decimal StandPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string StandFeatures { get; set; }
        public int SupplierId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Fair Fair { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMFAPayment> ADMFAPayments { get; set; }
    }
}
