//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMFAPayment
    {
        public int ID { get; set; }
        public int CompanyId { get; set; }
        public int FairId { get; set; }
        public Nullable<bool> FreeArea { get; set; }
        public Nullable<int> FreeAreaId { get; set; }
        public Nullable<decimal> FreeAreaTotalPrice { get; set; }
        public int AdditionalStandId { get; set; }
        public decimal AddiitionalStandTotalPrice { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal AmountNotPaid { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> DollarPrice { get; set; }
        public Nullable<decimal> EuroPrice { get; set; }
        public Nullable<decimal> TurkıshLira { get; set; }
    
        public virtual AdditionalStandMaterial AdditionalStandMaterial { get; set; }
        public virtual Company Company { get; set; }
        public virtual Fair Fair { get; set; }
        public virtual FreeArea FreeArea1 { get; set; }
    }
}
