//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetAndCurrentSale
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal ContractTotal { get; set; }
        public decimal AdditionalStandTotal { get; set; }
        public decimal OtherTotal { get; set; }
        public decimal ComisyonTotal { get; set; }
        public decimal KDVTotal { get; set; }
        public decimal CorporateTaxTotal { get; set; }
        public decimal ReserveFundTotal { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> DollarTotal { get; set; }
        public Nullable<decimal> EuroTotal { get; set; }
        public Nullable<decimal> TurkıshLiraTotal { get; set; }
        public Nullable<decimal> DollarExchangeRate { get; set; }
        public Nullable<decimal> EuroExchangeRate { get; set; }
    }
}
