//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContractPayment
    {
        public int ID { get; set; }
        public int ContractId { get; set; }
        public int CompanyId { get; set; }
        public int FairId { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> AmountNotPaid { get; set; }
        public Nullable<decimal> DollarPrice { get; set; }
        public Nullable<decimal> EuroPrice { get; set; }
        public Nullable<decimal> TurkıshLira { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Fair Fair { get; set; }
    }
}
