//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AdditionalStandMaterials = new HashSet<AdditionalStandMaterial>();
            this.ADMFAPayments = new HashSet<ADMFAPayment>();
            this.CatalogInputForms = new HashSet<CatalogInputForm>();
            this.CompanyContractPayments = new HashSet<CompanyContractPayment>();
            this.CompanyInformations = new HashSet<CompanyInformation>();
            this.CompanyNeeds = new HashSet<CompanyNeed>();
            this.FreeAreas = new HashSet<FreeArea>();
            this.HiddenDiscounts = new HashSet<HiddenDiscount>();
            this.Interviewees = new HashSet<Interviewee>();
            this.ParticipantHandbooks = new HashSet<ParticipantHandbook>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyOfficial { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Intercom { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int CountryId { get; set; }
        public int SectorId { get; set; }
        public int FairId { get; set; }
        public Nullable<int> FairAttendance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalStandMaterial> AdditionalStandMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMFAPayment> ADMFAPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogInputForm> CatalogInputForms { get; set; }
        public virtual Country Country { get; set; }
        public virtual Fair Fair { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyContractPayment> CompanyContractPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyInformation> CompanyInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyNeed> CompanyNeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeArea> FreeAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiddenDiscount> HiddenDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interviewee> Interviewees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantHandbook> ParticipantHandbooks { get; set; }
    }
}
