//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyNeed
    {
        public int ID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<short> InvitationNumber { get; set; }
        public Nullable<short> PosterNumber { get; set; }
        public Nullable<short> PersonelEntryCardNumber { get; set; }
        public Nullable<short> StaffParkingEntryCardNumber { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
