//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FreeArea()
        {
            this.ADMFAPayments = new HashSet<ADMFAPayment>();
        }
    
        public int ID { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public bool Electric { get; set; }
        public string KWNeed { get; set; }
        public Nullable<decimal> KWPrice { get; set; }
        public bool Water { get; set; }
        public string LTNeed { get; set; }
        public Nullable<decimal> LTPrice { get; set; }
        public bool WasteWater { get; set; }
        public string WLTNeed { get; set; }
        public Nullable<decimal> WLTPrice { get; set; }
        public bool CompressedAir { get; set; }
        public string AirNeed { get; set; }
        public Nullable<decimal> AirPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMFAPayment> ADMFAPayments { get; set; }
        public virtual Company Company { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
