//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int ProfessionId { get; set; }
        public int TicketTypeId { get; set; }
        public int FairId { get; set; }
        public string QrCodeImage { get; set; }
    
        public virtual Fair Fair { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
