//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int ID { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public System.DateTime OfferDate { get; set; }
        public int IntervieweeId { get; set; }
        public int SectorId { get; set; }
        public int CompanyProfileId { get; set; }
        public int FairId { get; set; }
        public int SaloonId { get; set; }
        public string Notes { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
        public virtual Fair Fair { get; set; }
        public virtual Interviewee Interviewee { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
        public virtual Saloon Saloon { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
