//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int ID { get; set; }
        public System.DateTime OfferDate { get; set; }
        public int SaloonId { get; set; }
        public int StandId { get; set; }
        public Nullable<int> OfferSquare { get; set; }
        public Nullable<decimal> SquarePrice { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> MaturityNumber { get; set; }
        public string PaymentPlan { get; set; }
        public System.DateTime OfferDeadline { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Saloon Saloon { get; set; }
        public virtual Stand Stand { get; set; }
    }
}
