//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairWorkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantHandbook
    {
        public int ID { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int FairId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Fair Fair { get; set; }
    }
}
